gz_ros_control:
  ros__parameters:
    hold_joints: true
    position_proportional_gain: 0.5

controller_manager:
  ros__parameters:
    update_rate: 1000

    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - swing_to_boom
      - boom_to_arm
      - arm_to_bucket
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      swing_to_boom:
        goal: 0.05
        # trajectory: 0.5
      boom_to_arm:
        goal: 0.05
        # trajectory: 0.5
      arm_to_bucket:
        goal: 0.05
        # trajectory: 0.5

    gains:
      swing_to_boom:
        p: 100000.0
        i: 1000.0
        d: 1000.0
        ff_velocity_scale: 1000.0
      boom_to_arm:
        p: 100000.0
        i: 1000.0
        d: 1000.0
        ff_velocity_scale: 1000.0
      arm_to_bucket:
        p: 100000.0
        i: 1000.0
        d: 1000.0
        ff_velocity_scale: 1000.0