# controller_manager:
#   ros__parameters:
#     update_rate: 100

#     slew_effort_controller:
#       type: effort_controllers/JointEffortController
#       joint: slew

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - slew
      - boom_to_swing
