controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    excavator_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: forward_command_controller/ForwardCommandController


excavator_controller:
  ros__parameters:
    joints:
      - swing_to_boom
      - boom_to_arm
      - arm_to_bucket

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0  # Hz
    action_monitor_rate: 20.0  # Hz

    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 100.0
      swing_to_boom:
        # trajectory: 0.1
        goal: 0.03
      boom_to_arm:
      #   # trajectory: 0.1
        goal: 0.03
      arm_to_bucket:
      #   # trajectory: 0.1
        goal: 0.03