controller_manager:
  ros__parameters:
    update_rate: 100

    swing_to_boom_controller:
      type: velocity_controllers/JointGroupVelocityController

    boom_to_arm_controller:
      type: velocity_controllers/JointGroupVelocityController

    arm_to_bucket_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

swing_to_boom_controller:
  ros__parameters:
    joints:
      - swing_to_boom

swing_to_boom_controller:
  ros__parameters:
    joints:
      - swing_to_boom

boom_to_arm_controller:
  ros__parameters:
    joints:
      - boom_to_arm

arm_to_bucket_controller:
  ros__parameters:
    joints:
      - arm_to_bucket