gz_ros_control:
  ros__parameters:
    hold_joints: true
    position_proportional_gain: 0.5

controller_manager:
  ros__parameters:
    update_rate: 1000

    manipulator_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - swing_to_boom
      - boom_to_arm
      - arm_to_bucket
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

