<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find sambot_description)/urdf/params.xacro"/>
    <xacro:macro name="gazebo_joint_dynamics" params="joint_name stiffness damping">
        <gazebo reference="${joint_name}">
            <stiffness>${stiffness}</stiffness>
            <damping>${damping}</damping>
            <pid>
                <p>1</p>
                <i>0</i>
                <d>0</d>
            </pid>
            <dynamics damping="5" friction="0.2"/>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gazebo_ros2_control_joints_effort" params="name effort_lim">
        <joint name="${name}">
            <command_interface name="effort">
                <param name="min">${-effort_lim}</param>
                <param name="max">${effort_lim}</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
            <!-- <state_interface name="effort"/> -->
        </joint>
    </xacro:macro>

    <xacro:macro name="simple_transmission" params="name">
        <transmission name="${name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- <xacro:gazebo_joint_dynamics joint_name="${excavator_slew_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${plow_to_base_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${arm_to_bucket_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${boom_to_arm_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${swing_to_boom_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${cabin_to_swing_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${left_spin_to_skid_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${left_free_to_skid_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${right_spin_to_skid_joint_name}" stiffness="100" damping="5"/>
    <xacro:gazebo_joint_dynamics joint_name="${right_free_to_skid_joint_name}" stiffness="100" damping="5"/> -->


    <xacro:simple_transmission name="${plow_to_base_joint_name}"/>
    <xacro:simple_transmission name="${excavator_slew_joint_name}"/>
    <xacro:simple_transmission name="${cabin_to_swing_joint_name}"/>
    <xacro:simple_transmission name="${swing_to_boom_joint_name}"/>
    <xacro:simple_transmission name="${boom_to_arm_joint_name}"/>
    <xacro:simple_transmission name="${arm_to_bucket_joint_name}"/>

    <xacro:macro name="dynamics_plugins">
        <ros2_control name="GazeboSystem" type="system">
            <!-- <hardware>
                <plugin>gazebo_ros2_control/GazeboSystem</plugin>
            </hardware> -->
            <hardware>
                <plugin>gz_ros2_control/GazeboSimSystem</plugin>
            </hardware>

            <xacro:gazebo_ros2_control_joints_effort name="${plow_to_base_joint_name}"  effort_lim="10000.0"/>
            <xacro:gazebo_ros2_control_joints_effort name="${excavator_slew_joint_name}" effort_lim="10000.0"/>
            <xacro:gazebo_ros2_control_joints_effort name="${cabin_to_swing_joint_name}"  effort_lim="10000.0"/>
            <xacro:gazebo_ros2_control_joints_effort name="${swing_to_boom_joint_name}"  effort_lim="30000.0"/>
            <xacro:gazebo_ros2_control_joints_effort name="${boom_to_arm_joint_name}"  effort_lim="10000.0"/>
            <xacro:gazebo_ros2_control_joints_effort name="${arm_to_bucket_joint_name}"  effort_lim="10000.0"/>

        </ros2_control>

        <gazebo>
            <!-- <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so"> -->
            <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
                <parameters>$(find sambot_description)/params/ec.yaml</parameters>
                <controller_manager_name>controller_manager</controller_manager_name>
            </plugin>
        </gazebo>
        <!-- <gazebo>
            <plugin name="two_wheeled_robot_diff_drive" filename="libgazebo_ros_diff_drive.so">
                <num_wheel_pairs>2</num_wheel_pairs>

                <left_joint>${left_spinning_to_turret_joint_name}</left_joint>
                <left_joint>${left_front_to_turret_joint_name}</left_joint>
                <right_joint>${right_spinning_to_turret_joint_name}</right_joint>
                <right_joint>${right_front_to_turret_joint_name}</right_joint>

                <wheel_separation>1.75</wheel_separation>
                <wheel_separation>1.75</wheel_separation>

                <wheel_diameter>${wheel_radius*2}</wheel_diameter>
                <wheel_diameter>${wheel_radius*2}</wheel_diameter>

                <max_wheel_torque>10000</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>

                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>

                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_link</robot_base_frame>
            </plugin>
        </gazebo> -->
    </xacro:macro>
</robot>
